version: '3.8'

services:
  producer:
    build:
      context: .
    volumes:
      - /home/peek/code/log_gen/logs:/app/logs:ro
    depends_on:
      - kafka
    command: python producer/producer.py

  consumer:
    build:
      context: .
    depends_on:
      - kafka
      - postgres
    command: python consumer/consumer.py

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  superset:
    image: apache/superset:latest
    environment:
      SUPERSET_LOAD_EXAMPLES: "yes"
      SUPERSET_SECRET_KEY: "a_very_secret_key"
      SUPERSET_DATABASE_URL: "postgresql+psycopg2://user:password@postgres:5432/logs_db"
    depends_on:
      - postgres
    ports:
      - "8088:8088"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data:

