name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version-file: "pyproject.toml"
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: uv run pytest tests

