name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Create virtual environment
        run: uv venv .venv

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Upload virtual environment as artifact
        uses: actions/upload-artifact@v3
        with:
          name: venv
          path: .venv

  tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download virtual environment artifact
        uses: actions/download-artifact@v3
        with:
          name: venv
          path: .venv

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Activate virtual environment
        run: |
          source .venv/bin/activate
          python -m pip install pytest

      - name: Run tests
        run: pytest
